# Generated by Django 5.2.5 on 2026-03-28 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_agent_kyc_document_agent_kyc_status_and_more'),
        ('leads', '0016_lead_customer_type_lead_is_overdue_and_more'),
        ('visits', '0002_sitevisit_checkin_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupVisitAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('pending', 'Pending')], db_index=True, default='pending', max_length=20)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['group_visit__visit_date', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='is_group_visit',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='is_no_show',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='GroupVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(db_index=True)),
                ('location', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_visits', to='agents.agent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_visits_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='group_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_visits', to='visits.groupvisit'),
        ),
        migrations.AddIndex(
            model_name='sitevisit',
            index=models.Index(fields=['lead', 'is_no_show'], name='visits_site_lead_id_bf17f8_idx'),
        ),
        migrations.AddField(
            model_name='groupvisitattendance',
            name='group_visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_rows', to='visits.groupvisit'),
        ),
        migrations.AddField(
            model_name='groupvisitattendance',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_visit_attendance', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='groupvisit',
            name='leads',
            field=models.ManyToManyField(blank=True, related_name='group_visits', through='visits.GroupVisitAttendance', to='leads.lead'),
        ),
        migrations.AddIndex(
            model_name='groupvisitattendance',
            index=models.Index(fields=['lead', 'attendance_status'], name='visits_grou_lead_id_1eba60_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupvisitattendance',
            unique_together={('group_visit', 'lead')},
        ),
        migrations.AddIndex(
            model_name='groupvisit',
            index=models.Index(fields=['agent', 'visit_date'], name='visits_grou_agent_i_1a02b9_idx'),
        ),
    ]
