# Generated by Django 5.2.5 on 2026-03-28 16:30

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0015_plan_analytics_access_plan_crm_access_and_more"),
        ("wallet", "0002_walletaccount_walletauditlog_walletledger_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reference_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("gateway", models.CharField(choices=[("razorpay", "Razorpay"), ("stripe", "Stripe"), ("dummy", "Demo Gateway")], db_index=True, default="dummy", max_length=20)),
                ("purpose", models.CharField(choices=[("wallet_topup", "Wallet Top-Up"), ("subscription", "Subscription"), ("property_booking", "Property Booking"), ("service", "Service Purchase")], db_index=True, default="wallet_topup", max_length=32)),
                ("status", models.CharField(choices=[("created", "Created"), ("pending", "Pending"), ("paid", "Paid"), ("failed", "Failed"), ("refunded", "Refunded"), ("cancelled", "Cancelled")], db_index=True, default="created", max_length=20)),
                ("provider_order_id", models.CharField(blank=True, db_index=True, default="", max_length=120)),
                ("provider_payment_id", models.CharField(blank=True, db_index=True, default="", max_length=120)),
                ("signature", models.CharField(blank=True, default="", max_length=255)),
                ("idempotency_key", models.CharField(blank=True, db_index=True, max_length=120, unique=True)),
                ("callback_url", models.URLField(blank=True)),
                ("return_url", models.URLField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="payment_orders", to="billing.order")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payment_orders", to=settings.AUTH_USER_MODEL)),
                ("wallet", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="payment_orders", to="wallet.wallet")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "status"], name="payments_pa_user_id_dcc045_idx"),
                    models.Index(fields=["gateway", "status"], name="payments_pa_gatewa_440d2b_idx"),
                    models.Index(fields=["purpose", "status"], name="payments_pa_purpos_6a6491_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reference_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("mode", models.CharField(choices=[("cash", "Cash"), ("upi", "UPI"), ("card", "Card"), ("wallet", "Wallet"), ("razorpay", "Razorpay"), ("stripe", "Stripe"), ("demo", "Demo")], default="demo", max_length=20)),
                ("status", models.CharField(choices=[("initiated", "Initiated"), ("authorized", "Authorized"), ("success", "Success"), ("failed", "Failed"), ("refunded", "Refunded")], db_index=True, default="initiated", max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("external_ref", models.CharField(blank=True, db_index=True, max_length=100)),
                ("payment_id", models.CharField(blank=True, db_index=True, default="", max_length=120)),
                ("gateway_order_id", models.CharField(blank=True, db_index=True, default="", max_length=120)),
                ("signature", models.CharField(blank=True, default="", max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("credited_to_wallet", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="payments", to="billing.order")),
                ("payment_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="transactions", to="payments.paymentorder")),
                ("user", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="payments", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "created_at"], name="payments_pa_user_id_5af67b_idx"),
                    models.Index(fields=["status", "created_at"], name="payments_pa_status_46784b_idx"),
                    models.Index(fields=["mode", "status"], name="payments_pa_mode_65b9a9_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyCashSummary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("business_date", models.DateField()),
                ("opening_cash", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("cash_in", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("cash_out", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("closing_cash", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("cashier", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cash_summaries", to=settings.AUTH_USER_MODEL)),
            ],
            options={"unique_together": {("cashier", "business_date")}},
        ),
    ]
