# Generated by Django 5.2.5 on 2026-03-28 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymentorder',
            new_name='payments_pa_user_id_367e5d_idx',
            old_name='payments_pa_user_id_dcc045_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentorder',
            new_name='payments_pa_gateway_23d222_idx',
            old_name='payments_pa_gatewa_440d2b_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentorder',
            new_name='payments_pa_purpose_45566a_idx',
            old_name='payments_pa_purpos_6a6491_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='payments_pa_user_id_ccae69_idx',
            old_name='payments_pa_user_id_5af67b_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='payments_pa_status_c4e513_idx',
            old_name='payments_pa_status_46784b_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='payments_pa_mode_102040_idx',
            old_name='payments_pa_mode_65b9a9_idx',
        ),
    ]
