# Generated by Django 5.2.11 on 2026-02-18 09:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=50)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('b2b_customer', 'B2B Customer'), ('b2c_customer', 'B2C Customer'), ('salesman', 'Salesman'), ('delivery_partner', 'Delivery Partner'), ('warehouse_staff', 'Warehouse Staff'), ('pos_cashier', 'POS Cashier')], max_length=40)),
                ('margin', models.DecimalField(decimal_places=2, max_digits=14)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_id', 'role'], name='users_commi_order_i_e1d2dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfileExt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('b2b_customer', 'B2B Customer'), ('b2c_customer', 'B2C Customer'), ('salesman', 'Salesman'), ('delivery_partner', 'Delivery Partner'), ('warehouse_staff', 'Warehouse Staff'), ('pos_cashier', 'POS Cashier')], db_index=True, default='b2c_customer', max_length=40)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('credit_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('commission_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('printer_preferences', models.JSONField(blank=True, default=dict)),
                ('scanner_preferences', models.JSONField(blank=True, default=dict)),
                ('pos_layout_preferences', models.JSONField(blank=True, default=dict)),
                ('is_active_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saas_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['role'], name='users_userp_role_42cfac_idx'), models.Index(fields=['updated_at'], name='users_userp_updated_1591a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='WalletLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('source', models.CharField(default='manual', max_length=60)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='users_walle_user_id_70631e_idx'), models.Index(fields=['source'], name='users_walle_source_61d0a3_idx')],
            },
        ),
    ]
