# Generated by Django 5.2.5 on 2026-03-21 09:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('core_settings', '0007_alter_featuresettings_feature'),
        ('leads', '0002_initial'),
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='lead',
            name='deal_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('google', 'Google'), ('telegram', 'Telegram'), ('youtube', 'YouTube'), ('api', 'API'), ('website', 'Website'), ('referral', 'Referral'), ('manual', 'Manual')], db_index=True, default='manual', max_length=30),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_progress', 'In Progress'), ('closed', 'Closed'), ('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold'), ('qualified', 'Qualified'), ('won', 'Won'), ('lost', 'Lost'), ('inactive', 'Inactive')], db_index=True, default='new', max_length=20),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', 'assigned_agent', 'status'], name='leads_lead_company_baa7ae_idx'),
        ),
    ]
