# Generated by Django 5.2.5 on 2026-03-21 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_address_agent_city_agent_experience_years_and_more'),
        ('core_settings', '0007_alter_featuresettings_feature'),
        ('leads', '0003_lead_assigned_agent_lead_deal_value_and_more'),
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='geo_location',
            field=models.JSONField(blank=True, default=dict, help_text='Lat/Lng if captured from maps or forms'),
        ),
        migrations.AddField(
            model_name='lead',
            name='preferred_location',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='lead',
            name='property_type',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('new', 'New'), ('qualified', 'Qualified'), ('visit', 'Visit Scheduled'), ('negotiation', 'Negotiation'), ('closed', 'Closed')], db_index=True, default='new', max_length=20),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['stage', 'created_at'], name='leads_lead_stage_6e412a_idx'),
        ),
    ]
