# Generated by Django 5.2.5 on 2026-03-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_budget_lead_geo_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_score',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='0-100 AI score'),
        ),
        migrations.AddField(
            model_name='lead',
            name='temperature',
            field=models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], db_index=True, default='warm', max_length=10),
        ),
    ]
