# Generated by Django 5.2.5 on 2026-03-23 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_alter_lead_company'),
        ('saas_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='saas_core.company'),
        ),
    ]
