# Generated by Django 5.2.5 on 2026-03-23 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_property_company'),
        ('saas_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='builder',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='builders', to='saas_core.company'),
        ),
        migrations.AddField(
            model_name='propertyproject',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_projects', to='saas_core.company'),
        ),
    ]
