# Generated by Django 5.2.5 on 2026-03-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_builder_company_propertyproject_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='followup_channel',
            field=models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_followup_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
