# Generated by Django 5.2.5 on 2026-03-24 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_agentcoveragearea_agent_approval_status_and_more'),
        ('leads', '0011_lead_followup_channel_lead_last_followup_at'),
        ('location', '0001_initial'),
        ('saas_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual'), ('reassign', 'Reassign')], default='auto', max_length=20)),
                ('matched_on', models.CharField(blank=True, choices=[('pin_code', 'Pin Code'), ('district', 'District'), ('state', 'State'), ('city', 'City'), ('manual', 'Manual'), ('fallback', 'Fallback')], default='', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='property_media/')),
                ('external_url', models.URLField(blank=True, default='')),
                ('caption', models.CharField(blank=True, default='', max_length=160)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PropertyWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='country',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='distribution_level',
            field=models.CharField(blank=True, choices=[('pin_code', 'Pin Code'), ('district', 'District'), ('state', 'State'), ('city', 'City'), ('manual', 'Manual'), ('fallback', 'Fallback')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='distribution_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='district',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='interested_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='leads.property'),
        ),
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lead',
            name='state',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='tehsil',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='village',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='area_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_properties', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='property',
            name='balcony',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='district',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='furnishing',
            field=models.CharField(choices=[('unfurnished', 'Unfurnished'), ('semi_furnished', 'Semi Furnished'), ('furnished', 'Furnished')], default='unfurnished', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent'), ('lease', 'Lease')], default='sale', max_length=12),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='parking',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='pin_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('sold', 'Sold'), ('rented', 'Rented')], db_index=True, default='pending_approval', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='tehsil',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='village',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('whatsapp_chatbot', 'WhatsApp Chatbot'), ('sms', 'SMS'), ('email', 'Email'), ('facebook', 'Facebook'), ('facebook_ads', 'Facebook Ads'), ('instagram', 'Instagram'), ('instagram_ads', 'Instagram Ads'), ('google', 'Google'), ('google_ads', 'Google Ads'), ('telegram', 'Telegram'), ('youtube', 'YouTube'), ('api', 'API'), ('website', 'Website'), ('landing_page', 'Landing Page'), ('missed_call', 'Missed Call'), ('referral', 'Referral'), ('manual', 'Manual')], db_index=True, default='manual', max_length=30),
        ),
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('follow_up', 'Follow Up'), ('visit_scheduled', 'Visit Scheduled'), ('qualified', 'Qualified'), ('visit', 'Visit Scheduled'), ('negotiation', 'Negotiation'), ('closed', 'Closed'), ('deal_closed', 'Deal Closed'), ('lost_lead', 'Lost Lead')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('flat', 'Flat'), ('apartment', 'Apartment'), ('villa', 'Villa'), ('land', 'Land'), ('plot', 'Plot'), ('commercial', 'Commercial'), ('office', 'Office'), ('shop', 'Shop'), ('warehouse', 'Warehouse')], default='apartment', max_length=20),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['pincode_text', 'district', 'state'], name='leads_lead_pincode_fa1b0b_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'listing_type', 'property_type'], name='leads_prope_status_e68b26_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'district', 'state'], name='leads_prope_city_ef8350_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['pin_code', 'status'], name='leads_prope_pin_cod_67afb2_idx'),
        ),
        migrations.AddField(
            model_name='leadassignmentlog',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_logs', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='leadassignmentlog',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadassignmentlog',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_logs', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='propertymedia',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='leads.property'),
        ),
        migrations.AddField(
            model_name='propertywishlist',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_entries', to='leads.property'),
        ),
        migrations.AddField(
            model_name='propertywishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_wishlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='leadassignmentlog',
            index=models.Index(fields=['lead', 'created_at'], name='leads_leada_lead_id_c44a2c_idx'),
        ),
        migrations.AddIndex(
            model_name='leadassignmentlog',
            index=models.Index(fields=['agent', 'created_at'], name='leads_leada_agent_i_abbd9f_idx'),
        ),
        migrations.AddIndex(
            model_name='propertymedia',
            index=models.Index(fields=['property', 'media_type', 'sort_order'], name='leads_prope_propert_0775ef_idx'),
        ),
        migrations.AddIndex(
            model_name='propertywishlist',
            index=models.Index(fields=['user', 'created_at'], name='leads_prope_user_id_368f98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='propertywishlist',
            unique_together={('property', 'user')},
        ),
    ]
