# Generated by Django 5.2.5 on 2026-03-24 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_agentverification_agent_license_number_and_more'),
        ('leads', '0012_leadassignmentlog_propertymedia_propertywishlist_and_more'),
        ('saas_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(db_index=True, max_length=120)),
                ('feature_value', models.CharField(blank=True, default='', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['feature_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('image_url', models.URLField(blank=True, default='')),
                ('caption', models.CharField(blank=True, default='', max_length=160)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PropertyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('district', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('state', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('pin_code', models.CharField(blank=True, db_index=True, default='', max_length=12)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='property_videos/')),
                ('video_url', models.URLField(blank=True, default='')),
                ('caption', models.CharField(blank=True, default='', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['company', 'status', 'created_at'], name='leads_prope_company_ab11c7_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['assigned_agent', 'status'], name='leads_prope_assigne_390eab_idx'),
        ),
        migrations.AddField(
            model_name='propertyfeature',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='leads.property'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='leads.property'),
        ),
        migrations.AddField(
            model_name='propertylocation',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_detail', to='leads.property'),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='leads.property'),
        ),
        migrations.AddIndex(
            model_name='propertyfeature',
            index=models.Index(fields=['property', 'feature_name'], name='leads_prope_propert_70ad00_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['property', 'is_primary', 'sort_order'], name='leads_prope_propert_99214a_idx'),
        ),
        migrations.AddIndex(
            model_name='propertylocation',
            index=models.Index(fields=['city', 'district', 'state'], name='leads_prope_city_80f497_idx'),
        ),
        migrations.AddIndex(
            model_name='propertylocation',
            index=models.Index(fields=['pin_code', 'updated_at'], name='leads_prope_pin_cod_ead7a9_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyvideo',
            index=models.Index(fields=['property', 'created_at'], name='leads_prope_propert_6ee2ea_idx'),
        ),
    ]
