# Generated by Django 5.2.5 on 2026-03-24 13:05

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_agentverification_agent_license_number_and_more'),
        ('leads', '0013_propertyfeature_propertyimage_propertylocation_and_more'),
        ('saas_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='builder',
            name='city',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='builder',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='builder',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='builder',
            name='registration_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='builder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='builder',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='property',
            name='aggregated_property',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='data_source',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='import_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='source_reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='propertyproject',
            name='city',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='propertyproject',
            name='completion_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyproject',
            name='construction_status',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='propertyproject',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='propertyproject',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='propertyproject',
            name='pre_launch',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='propertyproject',
            name='property_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='propertyproject',
            name='roi_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='propertyproject',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='propertyproject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='builder',
            index=models.Index(fields=['company_name', 'city'], name='leads_build_company_59f9e9_idx'),
        ),
        migrations.AddIndex(
            model_name='builder',
            index=models.Index(fields=['registration_number'], name='leads_build_registr_2533bd_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['aggregated_property', 'data_source'], name='leads_prope_aggrega_72b1d5_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['source_reference'], name='leads_prope_source__9d233f_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyproject',
            index=models.Index(fields=['city', 'approved'], name='leads_prope_city_8c5218_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyproject',
            index=models.Index(fields=['construction_status', 'completion_date'], name='leads_prope_constru_d25f0c_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyproject',
            index=models.Index(fields=['pre_launch', 'approved'], name='leads_prope_pre_lau_17d83d_idx'),
        ),
    ]
