# Generated by Django 5.2.5 on 2026-03-25 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_agent_commission_rate_agent_performance_score_and_more'),
        ('customers', '0002_customer_assigned_agent_and_more'),
        ('leads', '0014_builder_city_builder_contact_email_builder_metadata_and_more'),
        ('location', '0001_initial'),
        ('saas_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='followup',
            name='channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS'), ('call', 'Call')], db_index=True, default='whatsapp', max_length=20),
        ),
        migrations.AddField(
            model_name='followup',
            name='last_error',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='followup',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='agent_first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originated_leads', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='lead',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='lead',
            name='duplicate_reason',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='lead',
            name='interest_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('rent', 'Rent')], db_index=True, default='buy', max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_duplicate',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_reassigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('follow_up', 'Follow Up'), ('interested', 'Interested'), ('visit_scheduled', 'Visit Scheduled'), ('qualified', 'Qualified'), ('site_visit', 'Site Visit'), ('visit', 'Visit Scheduled'), ('negotiation', 'Negotiation'), ('converted', 'Converted'), ('closed', 'Closed'), ('deal_closed', 'Deal Closed'), ('lost_lead', 'Lost Lead')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('follow_up', 'Follow Up'), ('in_progress', 'In Progress'), ('converted', 'Converted'), ('closed', 'Closed'), ('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold'), ('qualified', 'Qualified'), ('won', 'Won'), ('lost', 'Lost'), ('inactive', 'Inactive')], db_index=True, default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='LeadAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual'), ('reassign', 'Reassign')], default='auto', max_length=20)),
                ('matched_on', models.CharField(blank=True, choices=[('pin_code', 'Pin Code'), ('district', 'District'), ('tehsil', 'Tehsil'), ('village', 'Village'), ('state', 'State'), ('city', 'City'), ('manual', 'Manual'), ('fallback', 'Fallback'), ('nearest', 'Nearest')], default='', max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('response_due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('first_contact_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_assignments', to='agents.agent')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('kind', models.CharField(choices=[('facebook_ads', 'Facebook Ads'), ('instagram_ads', 'Instagram Ads'), ('website_form', 'Website Form'), ('manual', 'Manual'), ('csv', 'CSV Upload'), ('web_scrape', 'Web Scraping'), ('api', 'API'), ('webhook', 'Webhook')], db_index=True, default='manual', max_length=20)),
                ('source_value', models.CharField(db_index=True, default='manual', max_length=30)),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=160)),
                ('verify_token', models.CharField(blank=True, default='', max_length=160)),
                ('endpoint_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('auto_assign', models.BooleanField(default=True)),
                ('default_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_sources', to='saas_core.company')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LeadImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('csv', 'CSV Upload'), ('webhook', 'Webhook'), ('api', 'API'), ('web_scrape', 'Web Scrape'), ('manual', 'Manual')], db_index=True, default='manual', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='lead_imports/')),
                ('external_reference', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('source_name', models.CharField(blank=True, default='', max_length=120)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('created_leads', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('error_report', models.JSONField(blank=True, default=list)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_import_batches', to='saas_core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_import_batches', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to='leads.leadsource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='source_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.leadsource'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_duplicate', 'created_at'], name='leads_lead_is_dupl_5b357b_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['converted_customer', 'converted_at'], name='leads_lead_convert_182971_idx'),
        ),
        migrations.AddIndex(
            model_name='leadassignment',
            index=models.Index(fields=['lead', 'is_active'], name='leads_leada_lead_id_fd538e_idx'),
        ),
        migrations.AddIndex(
            model_name='leadassignment',
            index=models.Index(fields=['agent', 'is_active'], name='leads_leada_agent_i_d23cf3_idx'),
        ),
        migrations.AddIndex(
            model_name='leadassignment',
            index=models.Index(fields=['response_due_at', 'is_active'], name='leads_leada_respons_72e382_idx'),
        ),
        migrations.AddIndex(
            model_name='leadsource',
            index=models.Index(fields=['company', 'is_active'], name='leads_leads_company_008484_idx'),
        ),
        migrations.AddIndex(
            model_name='leadsource',
            index=models.Index(fields=['slug', 'is_active'], name='leads_leads_slug_a86435_idx'),
        ),
        migrations.AddIndex(
            model_name='leadsource',
            index=models.Index(fields=['kind', 'is_active'], name='leads_leads_kind_09d4b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leadsource',
            unique_together={('company', 'slug')},
        ),
        migrations.AddIndex(
            model_name='leadimportbatch',
            index=models.Index(fields=['company', 'status', 'created_at'], name='leads_leadi_company_7231c0_idx'),
        ),
        migrations.AddIndex(
            model_name='leadimportbatch',
            index=models.Index(fields=['import_type', 'status'], name='leads_leadi_import__ac645d_idx'),
        ),
        migrations.AddIndex(
            model_name='leadimportbatch',
            index=models.Index(fields=['external_reference'], name='leads_leadi_externa_e725ae_idx'),
        ),
    ]
