# Generated by Django 5.2.5 on 2026-03-28 12:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_followup_attempts_followup_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='customer_type',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('investor', 'Investor'), ('reseller', 'Reseller')], db_index=True, default='buyer', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_overdue',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='no_show_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='reliability_score',
            field=models.PositiveIntegerField(db_index=True, default=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='stage_deadline',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='stage_updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyproject',
            name='launch_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyproject',
            name='launch_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='propertyproject',
            name='leads',
            field=models.ManyToManyField(blank=True, related_name='project_launches', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='propertyproject',
            name='pre_launch_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='propertyproject',
            name='status',
            field=models.CharField(choices=[('prelaunch', 'Prelaunch'), ('live', 'Live'), ('soldout', 'Sold Out')], db_index=True, default='prelaunch', max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('hold', 'On Hold')], db_index=True, default='planned', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='leads.propertyproject')),
                ('properties', models.ManyToManyField(blank=True, related_name='project_phases', to='leads.property')),
            ],
            options={
                'ordering': ['-start_date', 'id'],
                'indexes': [models.Index(fields=['project', 'status', 'start_date'], name='leads_proje_project_a5dbaa_idx'), models.Index(fields=['name', 'status'], name='leads_proje_name_efb69e_idx')],
            },
        ),
    ]
