# Generated by Django 5.2.5 on 2026-03-29 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_agent_assigned_location_agent_current_location'),
        ('leads', '0016_lead_customer_type_lead_is_overdue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='lock_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='locked_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_leads', to='agents.agent'),
        ),
    ]
