# Generated by Django 5.1.3 on 2025-12-08 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("billing", "0001_initial"),
        ("khataapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="party",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="khataapp.party",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="feature_toggle",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plan",
                to="billing.featuretoggle",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="plans", to="auth.group"
            ),
        ),
        migrations.AddField(
            model_name="billinginvoice",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billing_invoices",
                to="billing.plan",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="invoice",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="billing_subscription",
                to="billing.billinginvoice",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="billing_subscriptions",
                to="billing.plan",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billing_subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billing_stocks",
                to="billing.warehouse",
            ),
        ),
    ]
