# Generated by Django 5.1.3 on 2025-09-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("billing", "0002_alter_subscription_options_remove_plan_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="plans", to="auth.group"
            ),
        ),
    ]
