# Generated by Django 5.1.3 on 2025-09-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_alter_plan_options_remove_invoice_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentGateway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name shown in admin", max_length=80
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("razorpay", "Razorpay"),
                            ("phonepe", "PhonePe"),
                            ("dummy", "Dummy (test)"),
                        ],
                        default="razorpay",
                        max_length=30,
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("api_key", models.CharField(blank=True, max_length=255, null=True)),
                ("api_secret", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "checkout_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional provider checkout endpoint",
                        null=True,
                    ),
                ),
                (
                    "webhook_secret",
                    models.CharField(
                        blank=True,
                        help_text="Secret used to validate webhooks",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Payment Gateway",
                "verbose_name_plural": "Payment Gateways",
            },
        ),
    ]
