# Generated by Django 5.1.3 on 2025-09-18 06:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_paymentgateway"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="invoice",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
