# Generated by Django 5.2.5 on 2026-02-22

from django.db import migrations


FEATURE_REGISTRY = [
    {"key": "billing.invoices", "label": "Invoices", "group": "Billing"},
    {"key": "billing.returns", "label": "Returns", "group": "Billing"},
    {"key": "billing.credit_notes", "label": "Credit Notes", "group": "Billing"},
    {"key": "commerce.orders", "label": "Orders", "group": "Commerce"},
    {"key": "commerce.purchase", "label": "Purchase", "group": "Commerce"},
    {"key": "commerce.suppliers", "label": "Suppliers", "group": "Commerce"},
    {"key": "commerce.inventory", "label": "Inventory", "group": "Inventory"},
    {"key": "inventory.barcode", "label": "Barcode", "group": "Inventory"},
    {"key": "barcode.print", "label": "Barcode Print", "group": "Inventory"},
    {"key": "inventory.batch", "label": "Batch", "group": "Inventory"},
    {"key": "inventory.expiry", "label": "Expiry", "group": "Inventory"},
    {"key": "communication.whatsapp", "label": "WhatsApp Bot", "group": "Communication"},
    {"key": "whatsapp.orders", "label": "WhatsApp Orders", "group": "Communication"},
    {"key": "communication.sms", "label": "SMS", "group": "Communication"},
    {"key": "communication.email", "label": "Email", "group": "Communication"},
    {"key": "advanced.ai_reports", "label": "AI Reports", "group": "Advanced"},
    {"key": "advanced.api", "label": "API Access", "group": "Advanced"},
    {"key": "api.access", "label": "API Access", "group": "Advanced"},
    {"key": "advanced.automation", "label": "Automation", "group": "Advanced"},
    {"key": "settings.advanced", "label": "Advanced Settings", "group": "Advanced"},
    {"key": "multiuser", "label": "Multi-user", "group": "Advanced"},
    {"key": "reports.advanced", "label": "Advanced Reports", "group": "Advanced"},
    {"key": "payments.gateway", "label": "Payment Gateway", "group": "Advanced"},
    {"key": "field.agents", "label": "Field Agents", "group": "Advanced"},
    {"key": "chatbot.flows", "label": "Chatbot Flows", "group": "Communication"},
    {"key": "crm.dashboard", "label": "CRM Dashboard", "group": "Real Estate"},
    {"key": "crm.leads", "label": "Leads", "group": "Real Estate"},
    {"key": "crm.properties", "label": "Properties", "group": "Real Estate"},
    {"key": "crm.deals", "label": "Deals", "group": "Real Estate"},
    {"key": "crm.agents", "label": "Agents", "group": "Real Estate"},
    {"key": "crm.reports", "label": "Reports", "group": "Real Estate"},
    {"key": "crm.wallet", "label": "Wallet", "group": "Real Estate"},
    {"key": "crm.settings", "label": "Settings", "group": "Real Estate"},
    {"key": "crm.visits", "label": "Site Visits", "group": "Real Estate"},
    {"key": "crm.group_visits", "label": "Group Visits", "group": "Real Estate"},
    {"key": "crm.kyc", "label": "Agent KYC", "group": "Real Estate"},
    {"key": "crm.agent_transfers", "label": "Agent Transfers", "group": "Real Estate"},
    {"key": "crm.project_launch", "label": "Project Launch", "group": "Real Estate"},
    {"key": "crm.project_phases", "label": "Project Phases", "group": "Real Estate"},
    {"key": "crm.segmentation", "label": "Customer Segmentation", "group": "Real Estate"},
    {"key": "crm.pipeline_deadlines", "label": "Pipeline Deadlines", "group": "Real Estate"},
    {"key": "crm.sales_performance", "label": "Sales Performance", "group": "Real Estate"},
    {"key": "crm.payment_adjustments", "label": "Payment Adjustments", "group": "Real Estate"},
    {"key": "crm.admin_override", "label": "Admin Overrides", "group": "Real Estate"},
    {"key": "crm.inventory_holds", "label": "Inventory Holds", "group": "Real Estate"},
]


def sync_feature_registry(apps, schema_editor):
    FeatureRegistry = apps.get_model("billing", "FeatureRegistry")
    Plan = apps.get_model("billing", "Plan")
    PlanFeature = apps.get_model("billing", "PlanFeature")

    for index, item in enumerate(FEATURE_REGISTRY):
        FeatureRegistry.objects.update_or_create(
            key=item["key"],
            defaults={
                "label": item["label"],
                "group": item.get("group", "General"),
                "description": item.get("description", ""),
                "sort_order": index,
                "active": True,
            },
        )

    for plan in Plan.objects.all():
        for feature in FeatureRegistry.objects.filter(active=True):
            PlanFeature.objects.get_or_create(plan=plan, feature=feature, defaults={"enabled": True})


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0013_userfeatureoverride"),
    ]

    operations = [
        migrations.RunPython(sync_feature_registry, migrations.RunPython.noop),
    ]
