# Generated by Django 5.2.5 on 2026-03-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_sync_feature_registry'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='analytics_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='crm_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='marketing_tools_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_leads_per_month',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_property_listings',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
