# Generated by Django 5.2.5 on 2026-03-28 09:09

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_plan_analytics_access_plan_crm_access_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='provider',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('phonepe', 'PhonePe'), ('dummy', 'Dummy (Test Gateway)')], default='dummy', max_length=30),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('source_type', models.CharField(choices=[('wallet_recharge', 'Wallet Recharge'), ('property_booking', 'Property Booking'), ('service_purchase', 'Service Purchase'), ('manual', 'Manual')], db_index=True, default='manual', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=16)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('cgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('igst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('billing_name', models.CharField(blank=True, default='', max_length=160)),
                ('billing_email', models.EmailField(blank=True, default='', max_length=254)),
                ('billing_address', models.TextField(blank=True, default='')),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('company_gstin', models.CharField(blank=True, default='', max_length=20)),
                ('company_address', models.TextField(blank=True, default='')),
                ('issued_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('payment_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fintech_invoice', to='payments.paymentorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fintech_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='GSTDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_gstin', models.CharField(blank=True, default='', max_length=20)),
                ('customer_gstin', models.CharField(blank=True, default='', max_length=20)),
                ('place_of_supply', models.CharField(blank=True, default='', max_length=100)),
                ('hsn_sac', models.CharField(blank=True, default='9983', max_length=30)),
                ('is_interstate', models.BooleanField(default=False)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=Decimal('9.00'), max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=Decimal('9.00'), max_digits=5)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gst_detail', to='billing.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user', 'issued_at'], name='billing_inv_user_id_d79d28_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['source_type', 'status'], name='billing_inv_source__1ad134_idx'),
        ),
    ]
