# Generated by Django 5.2.5 on 2026-03-29 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_alter_paymentgateway_provider_invoice_gstdetail_and_more'),
        ('leads', '0017_lead_is_locked_lead_lock_reason_lead_locked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_invoices', to='leads.lead'),
        ),
    ]
