# Generated by Django 5.2.5 on 2026-03-25 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0014_builder_city_builder_contact_email_builder_metadata_and_more'),
        ('saas_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='requested', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_verifications', to='saas_core.company')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='leads.property')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_verification_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_verifications_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('sale_agreement', 'Sale Agreement'), ('property_document', 'Property Document'), ('identity', 'Identity Verification'), ('deal_contract', 'Deal Contract'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to='verification_documents/')),
                ('external_url', models.URLField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_documents_uploaded', to=settings.AUTH_USER_MODEL)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='verification.propertyverification')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='propertyverification',
            index=models.Index(fields=['company', 'status'], name='verificatio_company_528c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyverification',
            index=models.Index(fields=['property', 'status'], name='verificatio_propert_e0634e_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyverification',
            index=models.Index(fields=['requested_by', 'status'], name='verificatio_request_8e2f5b_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationdocument',
            index=models.Index(fields=['verification', 'document_type'], name='verificatio_verific_86018a_idx'),
        ),
    ]
