# Generated by Django 5.2.5 on 2026-03-21 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_settings', '0007_alter_featuresettings_feature'),
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=160)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('pincodes', models.JSONField(blank=True, default=list, help_text='List of PIN/ZIP codes the agent services (strings).')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('performance', models.JSONField(blank=True, default=dict)),
                ('last_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='core_settings.companysettings')),
                ('service_areas', models.ManyToManyField(blank=True, help_text='Optional normalized mapping to location.Pincode rows.', related_name='agents', to='location.pincode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='agents_agen_company_f3b4f2_idx'), models.Index(fields=['updated_at'], name='agents_agen_updated_be5503_idx')],
            },
        ),
    ]
