# Generated by Django 5.2.5 on 2026-03-21 11:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_address_agent_city_agent_experience_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentwallet',
            name='locked_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pending confirmation', max_digits=14),
        ),
    ]
