# Generated by Django 5.2.5 on 2026-03-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agent_last_latitude_agent_last_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='activity_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agent',
            name='avg_response_time_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agent',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='frozen_wallet',
            field=models.BooleanField(default=False, help_text='If true, payouts are withheld'),
        ),
        migrations.AddField(
            model_name='agent',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='last_logout_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='last_ping_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='mlm_level',
            field=models.PositiveIntegerField(default=0, help_text='Cached MLM depth level'),
        ),
        migrations.AddField(
            model_name='agent',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=16),
        ),
        migrations.AddField(
            model_name='agent',
            name='risk_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
