# Generated by Django 5.2.5 on 2026-03-24 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agent_activity_log_agent_avg_response_time_seconds_and_more'),
        ('core_settings', '0007_alter_featuresettings_feature'),
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCoverageArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default='', max_length=120)),
                ('state', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('district', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('tehsil', models.CharField(blank=True, default='', max_length=120)),
                ('village', models.CharField(blank=True, default='', max_length=120)),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('pin_code', models.CharField(blank=True, db_index=True, default='', max_length=12)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_primary', 'state', 'district', 'city', 'pin_code'],
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='agent',
            name='country',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='agent',
            name='district',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='agent',
            name='franchise_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='agent',
            name='pin_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='agent',
            name='tehsil',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='agent',
            name='village',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['approval_status', 'is_active'], name='agents_agen_approva_e4e3d5_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['state', 'district', 'pin_code'], name='agents_agen_state_ab909c_idx'),
        ),
        migrations.AddField(
            model_name='agentcoveragearea',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_areas', to='agents.agent'),
        ),
        migrations.AddIndex(
            model_name='agentcoveragearea',
            index=models.Index(fields=['agent', 'is_active'], name='agents_agen_agent_i_1872ce_idx'),
        ),
        migrations.AddIndex(
            model_name='agentcoveragearea',
            index=models.Index(fields=['pin_code', 'is_active'], name='agents_agen_pin_cod_a130cb_idx'),
        ),
        migrations.AddIndex(
            model_name='agentcoveragearea',
            index=models.Index(fields=['district', 'is_active'], name='agents_agen_distric_2457b6_idx'),
        ),
        migrations.AddIndex(
            model_name='agentcoveragearea',
            index=models.Index(fields=['state', 'is_active'], name='agents_agen_state_65740b_idx'),
        ),
    ]
