# Generated by Django 5.2.5 on 2026-03-24 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_agentcoveragearea_agent_approval_status_and_more'),
        ('core_settings', '0007_alter_featuresettings_feature'),
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('license', 'License'), ('pan', 'PAN'), ('aadhaar', 'Aadhaar'), ('agreement', 'Agreement'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('document_file', models.FileField(upload_to='agent_verifications/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='license_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['license_number'], name='agents_agen_license_1be640_idx'),
        ),
        migrations.AddField(
            model_name='agentverification',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='agentverification',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_verifications_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='agentverification',
            index=models.Index(fields=['agent', 'status', 'created_at'], name='agents_agen_agent_i_929a4c_idx'),
        ),
        migrations.AddIndex(
            model_name='agentverification',
            index=models.Index(fields=['document_type', 'status'], name='agents_agen_documen_dc96ee_idx'),
        ),
    ]
