# Generated by Django 5.2.5 on 2026-03-25 10:08

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_agentverification_agent_license_number_and_more'),
        ('core_settings', '0007_alter_featuresettings_feature'),
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='agent',
            name='performance_score',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['performance_score', 'is_active'], name='agents_agen_perform_7ba4ad_idx'),
        ),
    ]
