# Generated by Django 5.2.5 on 2026-03-28 12:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_agent_commission_rate_agent_performance_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='kyc_document',
            field=models.FileField(blank=True, null=True, upload_to='agent_kyc/'),
        ),
        migrations.AddField(
            model_name='agent',
            name='kyc_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='agent',
            name='kyc_verified_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='agentperformancesnapshot',
            name='closed_leads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentperformancesnapshot',
            name='closing_ratio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7),
        ),
        migrations.AddField(
            model_name='agentperformancesnapshot',
            name='total_leads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AgentTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('leads', 'Leads'), ('deals', 'Deals'), ('both', 'Both')], db_index=True, default='both', max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('reassigned_leads', models.PositiveIntegerField(default=0)),
                ('reassigned_deals', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('new_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='agents.agent')),
                ('old_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='agents.agent')),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_transfers_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['old_agent', 'new_agent', 'created_at'], name='agents_agen_old_age_5cd918_idx'), models.Index(fields=['transfer_type', 'created_at'], name='agents_agen_transfe_1099a7_idx')],
            },
        ),
    ]
