# Generated by Django 5.2.5 on 2026-03-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_agent_kyc_document_agent_kyc_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='assigned_location',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agent',
            name='current_location',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
