# Generated by Django 5.2.11 on 2026-02-19 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_mode', models.CharField(choices=[('POS', 'POS Embedded'), ('TABLET', 'Tablet'), ('MOBILE', 'Mobile'), ('DESKTOP', 'Desktop'), ('ADMIN_SUPER', 'Admin Super Control'), ('AUTO', 'Auto')], db_index=True, default='DESKTOP', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_mode_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Mode',
                'verbose_name_plural': 'System Mode',
            },
        ),
    ]
