# Generated by Django 5.2.11 on 2026-02-19 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_risk_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-risk_score', '-last_calculated'],
                'unique_together': {('customer',)},
            },
        ),
        migrations.CreateModel(
            name='ProductDemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_date', models.DateField(db_index=True)),
                ('predicted_quantity', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_demand_forecasts', to='products.product')),
            ],
            options={
                'ordering': ['predicted_date', 'product_id'],
                'indexes': [models.Index(fields=['predicted_date'], name='ai_engine_p_predict_baff8e_idx')],
                'unique_together': {('product', 'predicted_date')},
            },
        ),
        migrations.CreateModel(
            name='SalesmanScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_score', models.IntegerField(default=0)),
                ('risk_flag', models.BooleanField(default=False)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_salesman_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performance_score', '-calculated_at'],
                'unique_together': {('salesman',)},
            },
        ),
    ]
