# Generated by Django 5.2.5 on 2026-03-25 08:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0014_builder_city_builder_contact_email_builder_metadata_and_more'),
        ('saas_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('summary', models.CharField(blank=True, default='', max_length=240)),
                ('description', models.TextField(blank=True, default='')),
                ('state', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('district', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('income_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('ownership_status', models.CharField(choices=[('first_time', 'First Time Buyer'), ('existing_owner', 'Existing Owner'), ('any', 'Any')], default='any', max_length=20)),
                ('apply_url', models.URLField(blank=True, default='')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='saas_core.company')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserSchemeMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('location', models.CharField(blank=True, default='', max_length=160)),
                ('ownership_status', models.CharField(blank=True, default='', max_length=20)),
                ('match_score', models.PositiveIntegerField(db_index=True, default=0)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('saved', 'Saved'), ('applied', 'Applied')], db_index=True, default='matched', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheme_matches', to='saas_core.company')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheme_matches', to='leads.property')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='schemes.scheme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-match_score', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scheme',
            index=models.Index(fields=['company', 'active'], name='schemes_sch_company_376cbb_idx'),
        ),
        migrations.AddIndex(
            model_name='scheme',
            index=models.Index(fields=['state', 'district', 'city'], name='schemes_sch_state_a60c0e_idx'),
        ),
        migrations.AddIndex(
            model_name='scheme',
            index=models.Index(fields=['ownership_status'], name='schemes_sch_ownersh_b6c494_idx'),
        ),
        migrations.AddIndex(
            model_name='userschemematch',
            index=models.Index(fields=['company', 'status'], name='schemes_use_company_17ff51_idx'),
        ),
        migrations.AddIndex(
            model_name='userschemematch',
            index=models.Index(fields=['user', 'status'], name='schemes_use_user_id_ed3ebe_idx'),
        ),
        migrations.AddIndex(
            model_name='userschemematch',
            index=models.Index(fields=['scheme', 'status'], name='schemes_use_scheme__c51d74_idx'),
        ),
    ]
