# Generated by Django 5.2.11 on 2026-02-18 09:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('salesman_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('delivery_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommissionPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margin_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('salesman_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('delivery_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('company_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_payouts', to='orders.order')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commission.commissionrule')),
            ],
            options={
                'indexes': [models.Index(fields=['order', 'created_at'], name='commission__order_i_22d4e3_idx')],
            },
        ),
    ]
