# Generated by Django 5.2.5 on 2026-03-24 13:05

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0007_agentverification_agent_license_number_and_more'),
        ('customers', '0001_initial'),
        ('deals', '0004_deal_agent_share_percent_deal_closing_date_and_more'),
        ('leads', '0013_propertyfeature_propertyimage_propertylocation_and_more'),
        ('saas_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=160)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('investment_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('preferred_cities', models.JSONField(blank=True, default=list)),
                ('property_type_preferences', models.JSONField(blank=True, default=list)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='medium', max_length=10)),
                ('min_roi_percent', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('alerts_enabled', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investors', to='saas_core.company')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestorMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('expected_roi_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('match_reason', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('notified', 'Notified'), ('viewed', 'Viewed'), ('converted', 'Converted'), ('dismissed', 'Dismissed')], db_index=True, default='new', max_length=20)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investor_matches', to='leads.propertyproject')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investor_matches', to='leads.property')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='intelligence.investorprofile')),
            ],
            options={
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PremiumLeadListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('exclusive', 'Exclusive'), ('hot', 'Hot'), ('verified', 'Verified')], db_index=True, default='hot', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('expired', 'Expired')], db_index=True, default='available', max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('buyer_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premium_leads_purchased', to='agents.agent')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premium_lead_listings', to='saas_core.company')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium_listing', to='leads.lead')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premium_leads_listed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_transaction_ref', models.CharField(blank=True, default='', max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('purchased_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('buyer_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_purchases', to='agents.agent')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_purchases', to='leads.lead')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='intelligence.premiumleadlisting')),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceTrendSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True)),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('district', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('property_type', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('average_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('price_change_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('historical_prices', models.JSONField(blank=True, default=list)),
                ('sample_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_trends', to='saas_core.company')),
            ],
            options={
                'ordering': ['-snapshot_date', '-average_price'],
            },
        ),
        migrations.CreateModel(
            name='PropertyAlertSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_location', models.CharField(blank=True, default='', max_length=160)),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('district', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('state', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('pin_code', models.CharField(blank=True, db_index=True, default='', max_length=12)),
                ('property_type', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('min_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('channels', models.JSONField(blank=True, default=list, help_text='email/sms/whatsapp/in_app')),
                ('trigger_types', models.JSONField(blank=True, default=list, help_text='new_property/price_drop/similar_property/builder_launch')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_alert_subscriptions', to='saas_core.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_subscriptions', to='customers.customer')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(db_index=True, max_length=120)),
                ('source_type', models.CharField(choices=[('public', 'Public Source'), ('partner', 'Partner Feed'), ('internal', 'Internal Feed')], db_index=True, default='partner', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_count', models.PositiveIntegerField(default=0)),
                ('inserted_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('normalized_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_import_batches', to='saas_core.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AggregatedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=120)),
                ('source_reference', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('title', models.CharField(max_length=200)),
                ('normalized_title', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('district', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('state', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('pin_code', models.CharField(blank=True, db_index=True, default='', max_length=12)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('property_type', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('duplicate_key', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('is_duplicate', models.BooleanField(db_index=True, default=False)),
                ('aggregated_property', models.BooleanField(db_index=True, default=True)),
                ('import_date', models.DateTimeField(db_index=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('normalized_payload', models.JSONField(blank=True, default=dict)),
                ('enrichment_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_properties', to='saas_core.company')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='intelligence.aggregatedproperty')),
                ('matched_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aggregated_records', to='leads.property')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='intelligence.propertyimportbatch')),
            ],
            options={
                'ordering': ['-import_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RealEstateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('sale_agreement', 'Sale Agreement'), ('property_document', 'Property Document'), ('identity_verification', 'Identity Verification'), ('deal_contract', 'Deal Contract'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('access_scope', models.CharField(choices=[('admin', 'Admin Only'), ('agent', 'Agent Access'), ('customer', 'Customer Access'), ('shared', 'Shared')], db_index=True, default='admin', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=160)),
                ('file', models.FileField(upload_to='real_estate_documents/')),
                ('encrypted', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='agents.agent')),
                ('builder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='leads.builder')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_documents', to='saas_core.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customers.customer')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='deals.deal')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secure_documents', to='leads.lead')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='leads.propertyproject')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='leads.property')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_estate_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandHeatmapSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True)),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('district', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('search_count', models.PositiveIntegerField(default=0)),
                ('lead_count', models.PositiveIntegerField(default=0)),
                ('property_view_count', models.PositiveIntegerField(default=0)),
                ('closed_deal_count', models.PositiveIntegerField(default=0)),
                ('supply_count', models.PositiveIntegerField(default=0)),
                ('demand_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('low_supply_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('hot_investment_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demand_heatmaps', to='saas_core.company')),
            ],
            options={
                'ordering': ['-snapshot_date', '-demand_score'],
                'indexes': [models.Index(fields=['company', 'snapshot_date'], name='intelligenc_company_33aa38_idx'), models.Index(fields=['city', 'district', 'snapshot_date'], name='intelligenc_city_358057_idx')],
                'unique_together': {('company', 'snapshot_date', 'city', 'district')},
            },
        ),
        migrations.AddIndex(
            model_name='investorprofile',
            index=models.Index(fields=['company', 'active', 'risk_level'], name='intelligenc_company_6a4be2_idx'),
        ),
        migrations.AddIndex(
            model_name='investorprofile',
            index=models.Index(fields=['investment_budget', 'active'], name='intelligenc_investm_aa4448_idx'),
        ),
        migrations.AddIndex(
            model_name='investormatch',
            index=models.Index(fields=['investor', 'status'], name='intelligenc_investo_f9b8c0_idx'),
        ),
        migrations.AddIndex(
            model_name='investormatch',
            index=models.Index(fields=['status', 'created_at'], name='intelligenc_status_083a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='premiumleadlisting',
            index=models.Index(fields=['company', 'status', 'category'], name='intelligenc_company_408f86_idx'),
        ),
        migrations.AddIndex(
            model_name='premiumleadlisting',
            index=models.Index(fields=['status', 'expires_at'], name='intelligenc_status_5dfbf3_idx'),
        ),
        migrations.AddIndex(
            model_name='leadpurchase',
            index=models.Index(fields=['buyer_agent', 'purchased_at'], name='intelligenc_buyer_a_ba4eb7_idx'),
        ),
        migrations.AddIndex(
            model_name='pricetrendsnapshot',
            index=models.Index(fields=['company', 'snapshot_date'], name='intelligenc_company_d668f3_idx'),
        ),
        migrations.AddIndex(
            model_name='pricetrendsnapshot',
            index=models.Index(fields=['city', 'district', 'property_type'], name='intelligenc_city_58d4ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricetrendsnapshot',
            unique_together={('company', 'snapshot_date', 'city', 'district', 'property_type')},
        ),
        migrations.AddIndex(
            model_name='propertyalertsubscription',
            index=models.Index(fields=['company', 'is_active'], name='intelligenc_company_f81b98_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyalertsubscription',
            index=models.Index(fields=['city', 'district', 'property_type'], name='intelligenc_city_8c7cfe_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimportbatch',
            index=models.Index(fields=['company', 'status', 'scheduled_for'], name='intelligenc_company_2d6a6c_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimportbatch',
            index=models.Index(fields=['source_name', 'created_at'], name='intelligenc_source__62af5e_idx'),
        ),
        migrations.AddIndex(
            model_name='aggregatedproperty',
            index=models.Index(fields=['company', 'duplicate_key'], name='intelligenc_company_9fa2bd_idx'),
        ),
        migrations.AddIndex(
            model_name='aggregatedproperty',
            index=models.Index(fields=['city', 'district', 'state', 'property_type'], name='intelligenc_city_d85a3f_idx'),
        ),
        migrations.AddIndex(
            model_name='aggregatedproperty',
            index=models.Index(fields=['source', 'source_reference'], name='intelligenc_source_5c901a_idx'),
        ),
        migrations.AddIndex(
            model_name='realestatedocument',
            index=models.Index(fields=['company', 'document_type', 'created_at'], name='intelligenc_company_5a72ef_idx'),
        ),
        migrations.AddIndex(
            model_name='realestatedocument',
            index=models.Index(fields=['access_scope', 'created_at'], name='intelligenc_access__58479f_idx'),
        ),
    ]
