# Generated by Django 5.2.x on 2026-02-23

import decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
        ("commerce", "0013_order_bill_sundry"),
    ]

    operations = [
        migrations.CreateModel(
            name="LedgerAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(help_text="Stable code (e.g. CASH, SALES, OUTPUT_GST_18, PARTY_123).", max_length=64)),
                ("name", models.CharField(max_length=200)),
                ("account_type", models.CharField(choices=[("asset", "Asset"), ("liability", "Liability"), ("income", "Income"), ("expense", "Expense"), ("equity", "Equity"), ("other", "Other")], db_index=True, default="other", max_length=20)),
                ("is_system", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner", models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name="gl_accounts", to=settings.AUTH_USER_MODEL)),
                ("party", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="gl_accounts", to="accounts.userprofile")),
            ],
            options={
                "ordering": ["code"],
                "indexes": [
                    models.Index(fields=["owner", "account_type"], name="idx_glacc_owner_type"),
                    models.Index(fields=["owner", "is_system"], name="idx_glacc_owner_system"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("owner", "code"), name="uniq_gl_account_owner_code"),
                    models.UniqueConstraint(condition=models.Q(("party__isnull", False)), fields=("owner", "party"), name="uniq_gl_account_owner_party"),
                ],
            },
        ),
        migrations.CreateModel(
            name="JournalVoucher",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(db_index=True, default=django.utils.timezone.now)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("posted", "Posted"), ("cancelled", "Cancelled")], db_index=True, default="draft", max_length=20)),
                ("narration", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner", models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name="journal_vouchers", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-date", "-id"],
                "indexes": [
                    models.Index(fields=["owner", "date"], name="idx_jv_owner_date"),
                    models.Index(fields=["owner", "status", "date"], name="idx_jv_owner_status_date"),
                ],
            },
        ),
        migrations.CreateModel(
            name="LedgerTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("voucher_type", models.CharField(choices=[("sales_invoice", "Sales Invoice"), ("purchase_invoice", "Purchase Invoice"), ("expense", "Expense"), ("receipt", "Receipt"), ("payment", "Payment"), ("journal", "Journal")], db_index=True, max_length=30)),
                ("date", models.DateField(db_index=True, default=django.utils.timezone.now)),
                ("reference_type", models.CharField(db_index=True, max_length=100)),
                ("reference_id", models.PositiveBigIntegerField(db_index=True)),
                ("reference_no", models.CharField(blank=True, default="", max_length=64)),
                ("narration", models.TextField(blank=True, default="")),
                ("total_debit", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("total_credit", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner", models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name="gl_transactions", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-date", "-id"],
                "indexes": [
                    models.Index(fields=["owner", "date"], name="idx_gltxn_owner_date"),
                    models.Index(fields=["owner", "voucher_type", "date"], name="idx_gltxn_owner_type_date"),
                    models.Index(fields=["owner", "reference_type", "reference_id"], name="idx_gltxn_owner_ref"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("owner", "voucher_type", "reference_type", "reference_id"), name="uniq_gl_txn_owner_source"),
                    models.CheckConstraint(check=models.Q(("total_credit__gte", 0), ("total_debit__gte", 0)), name="gl_txn_totals_non_negative"),
                    models.CheckConstraint(check=models.Q(("total_debit", models.F("total_credit"))), name="gl_txn_totals_balanced"),
                ],
            },
        ),
        migrations.CreateModel(
            name="StockTransfer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(db_index=True, default=django.utils.timezone.now)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("posted", "Posted"), ("cancelled", "Cancelled")], db_index=True, default="draft", max_length=20)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("from_warehouse", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stock_transfers_out", to="commerce.warehouse")),
                ("owner", models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name="stock_transfers", to=settings.AUTH_USER_MODEL)),
                ("to_warehouse", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stock_transfers_in", to="commerce.warehouse")),
            ],
            options={
                "ordering": ["-date", "-id"],
                "indexes": [
                    models.Index(fields=["owner", "date"], name="idx_trf_owner_date"),
                    models.Index(fields=["owner", "status", "date"], name="idx_trf_owner_status_date"),
                ],
            },
        ),
        migrations.CreateModel(
            name="StockLedger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(db_index=True, default=django.utils.timezone.now)),
                ("movement", models.CharField(choices=[("in", "In"), ("out", "Out")], db_index=True, max_length=3)),
                ("quantity_in", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("quantity_out", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("reference_type", models.CharField(db_index=True, max_length=100)),
                ("reference_id", models.PositiveBigIntegerField(db_index=True)),
                ("reference_line_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("owner", models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name="stock_ledger_entries", to=settings.AUTH_USER_MODEL)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stock_ledger_entries", to="commerce.product")),
                ("warehouse", models.ForeignKey(blank=True, help_text="Nullable until warehouse is captured in source flows.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name="stock_ledger_entries", to="commerce.warehouse")),
            ],
            options={
                "ordering": ["-date", "-id"],
                "indexes": [
                    models.Index(fields=["owner", "date"], name="idx_stock_owner_date"),
                    models.Index(fields=["owner", "product", "date"], name="idx_stock_owner_prod_date"),
                    models.Index(fields=["owner", "warehouse", "date"], name="idx_stock_owner_wh_date"),
                    models.Index(fields=["owner", "reference_type", "reference_id"], name="idx_stock_owner_ref"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("owner", "reference_type", "reference_id", "reference_line_id", "product", "movement"), name="uniq_stock_ledger_ref_line_product"),
                    models.CheckConstraint(check=models.Q(("quantity_in__gte", 0), ("quantity_out__gte", 0)), name="stock_ledger_non_negative"),
                    models.CheckConstraint(check=(models.Q(("quantity_in", 0), ("quantity_out__gt", 0)) | models.Q(("quantity_in__gt", 0), ("quantity_out", 0))), name="stock_ledger_one_side_only"),
                    models.CheckConstraint(check=(models.Q(("movement", "in"), ("quantity_in__gt", 0), ("quantity_out", 0)) | models.Q(("movement", "out"), ("quantity_out__gt", 0), ("quantity_in", 0))), name="stock_ledger_movement_match"),
                ],
            },
        ),
        migrations.CreateModel(
            name="StockTransferItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=14)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stock_transfer_items", to="commerce.product")),
                ("transfer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="ledger.stocktransfer")),
            ],
            options={
                "indexes": [models.Index(fields=["transfer", "product"], name="idx_trfi_trf_prod")],
            },
        ),
        migrations.CreateModel(
            name="JournalVoucherLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(blank=True, default="", max_length=255)),
                ("debit", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("credit", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="journal_lines", to="ledger.ledgeraccount")),
                ("party", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="journal_lines", to="accounts.userprofile")),
                ("voucher", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="ledger.journalvoucher")),
            ],
            options={
                "ordering": ["id"],
                "indexes": [models.Index(fields=["voucher", "account"], name="idx_jvl_voucher_account")],
                "constraints": [
                    models.CheckConstraint(check=models.Q(("credit__gte", 0), ("debit__gte", 0)), name="journal_line_non_negative"),
                    models.CheckConstraint(check=(models.Q(("credit", 0), ("debit__gt", 0)) | models.Q(("credit__gt", 0), ("debit", 0))), name="journal_line_one_side_only"),
                ],
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("line_no", models.PositiveSmallIntegerField(default=1)),
                ("description", models.CharField(blank=True, default="", max_length=255)),
                ("debit", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("credit", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="entries", to="ledger.ledgeraccount")),
                ("party", models.ForeignKey(blank=True, help_text="Optional party sub-ledger for this line.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name="gl_entries", to="accounts.userprofile")),
                ("transaction", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="entries", to="ledger.ledgertransaction")),
            ],
            options={
                "ordering": ["transaction_id", "line_no", "id"],
                "indexes": [
                    models.Index(fields=["transaction", "line_no"], name="idx_glent_txn_line"),
                    models.Index(fields=["account"], name="idx_glent_account"),
                    models.Index(fields=["party"], name="idx_glent_party"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("transaction", "line_no"), name="uniq_gl_entry_txn_line"),
                    models.CheckConstraint(check=models.Q(("credit__gte", 0), ("debit__gte", 0)), name="gl_entry_non_negative"),
                    models.CheckConstraint(check=(models.Q(("credit", 0), ("debit__gt", 0)) | models.Q(("credit__gt", 0), ("debit", 0))), name="gl_entry_one_side_only"),
                ],
            },
        ),
    ]
