# Generated by Django 5.2.5 on 2026-02-23 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0013_order_bill_sundry'),
        ('khataapp', '0007_offlinemessage_recipient_mobile_and_more'),
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='journalvoucherline',
            name='journal_line_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='ledgerentry',
            name='gl_entry_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='ledgertransaction',
            name='gl_txn_totals_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='stockledger',
            name='stock_ledger_one_side_only',
        ),
        migrations.RemoveConstraint(
            model_name='stockledger',
            name='stock_ledger_movement_match',
        ),
        migrations.AddConstraint(
            model_name='journalvoucherline',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0), ('credit__gte', 0)), name='journal_line_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0), ('credit__gte', 0)), name='gl_entry_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='ledgertransaction',
            constraint=models.CheckConstraint(condition=models.Q(('total_debit__gte', 0), ('total_credit__gte', 0)), name='gl_txn_totals_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockledger',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('quantity_in__gt', 0), ('quantity_out', 0)), models.Q(('quantity_in', 0), ('quantity_out__gt', 0)), _connector='OR'), name='stock_ledger_one_side_only'),
        ),
        migrations.AddConstraint(
            model_name='stockledger',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement', 'in'), ('quantity_in__gt', 0), ('quantity_out', 0)), models.Q(('movement', 'out'), ('quantity_in', 0), ('quantity_out__gt', 0)), _connector='OR'), name='stock_ledger_movement_match'),
        ),
    ]
