# Generated by Django 5.2.5 on 2026-03-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('domain', models.CharField(blank=True, default='', max_length=160)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logo/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
