# Generated by Django 5.1.3 on 2025-12-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("mobile", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
            ],
            options={
                "verbose_name": "Company Setting",
                "verbose_name_plural": "Company Settings",
            },
        ),
        migrations.CreateModel(
            name="UISettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme_mode",
                    models.CharField(
                        choices=[("light", "Light"), ("dark", "Dark")],
                        default="light",
                        max_length=10,
                    ),
                ),
                ("primary_color", models.CharField(default="#2563eb", max_length=20)),
                ("secondary_color", models.CharField(default="#0ea5e9", max_length=20)),
                ("sidebar_color", models.CharField(default="#111827", max_length=20)),
            ],
            options={
                "verbose_name": "UI Setting",
                "verbose_name_plural": "UI Settings",
            },
        ),
    ]
