# Generated by Django 5.1.3 on 2025-12-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_settings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("currency_symbol", models.CharField(default="₹", max_length=10)),
                ("financial_year_start", models.DateField()),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("enable_notifications", models.BooleanField(default=True)),
                ("enable_chat", models.BooleanField(default=True)),
                ("allow_user_signup", models.BooleanField(default=True)),
                ("allow_social_login", models.BooleanField(default=True)),
                ("show_profit_loss", models.BooleanField(default=True)),
                ("show_daily_summary", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FeatureSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("otp", "OTP System"),
                            ("emi", "EMI"),
                            ("gst", "GST"),
                            ("chat", "Chat"),
                            ("payment_gateway", "Payment Gateway"),
                            ("notification", "Notifications"),
                            ("daily_summary", "Daily Summary"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("config", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="ModuleSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("party", "Party"),
                            ("transaction", "Transaction"),
                            ("commerce", "Commerce"),
                            ("billing", "Billing"),
                            ("stock", "Stock"),
                            ("warehouse", "Warehouse"),
                            ("payment", "Payment"),
                            ("subscription", "Subscription"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("settings", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="SaaSSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enable_multi_company", models.BooleanField(default=False)),
                ("enable_multi_user", models.BooleanField(default=True)),
                ("enable_subscription", models.BooleanField(default=True)),
                ("enable_trial", models.BooleanField(default=True)),
                ("trial_days", models.PositiveIntegerField(default=7)),
                ("enable_audit_logs", models.BooleanField(default=True)),
                ("enable_api_access", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name="uisettings",
            options={},
        ),
        migrations.RemoveField(
            model_name="uisettings",
            name="sidebar_color",
        ),
        migrations.AddField(
            model_name="uisettings",
            name="danger_color",
            field=models.CharField(default="#dc2626", max_length=20),
        ),
        migrations.AddField(
            model_name="uisettings",
            name="show_commerce",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="uisettings",
            name="show_dashboard",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="uisettings",
            name="show_party",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="uisettings",
            name="show_reports",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="uisettings",
            name="show_settings",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="uisettings",
            name="show_transaction",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="uisettings",
            name="sidebar_collapsed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="uisettings",
            name="sidebar_position",
            field=models.CharField(
                choices=[("left", "Left"), ("right", "Right")],
                default="left",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="uisettings",
            name="success_color",
            field=models.CharField(default="#16a34a", max_length=20),
        ),
        migrations.AddField(
            model_name="uisettings",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="uisettings",
            name="primary_color",
            field=models.CharField(default="#4f46e5", max_length=20),
        ),
        migrations.AlterField(
            model_name="uisettings",
            name="theme_mode",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark")],
                default="light",
                max_length=20,
            ),
        ),
    ]
