# Generated by Django 5.2.5 on 2026-03-28 09:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0007_alter_featuresettings_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='address_line',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='default_gst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='gstin',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='invoice_prefix',
            field=models.CharField(blank=True, default='INV', max_length=12),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='state_code',
            field=models.CharField(blank=True, default='09', max_length=10),
        ),
    ]
