# Generated by Django 5.2.5 on 2025-12-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[("SALE", "Sale"), ("PURCHASE", "Purchase")],
                default="SALE",
                max_length=10,
            ),
        ),
    ]
