# Generated by Django 5.1.3 on 2025-12-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0003_order_order_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="gst_type",
            field=models.CharField(
                choices=[("GST", "GST"), ("NON_GST", "Non GST")],
                default="NON_GST",
                max_length=10,
            ),
        ),
    ]
