# Generated by Django 5.1.3 on 2025-12-23 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0004_invoice_gst_type"),
        ("khataapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesVoucher",
            fields=[
                ("invoice_no", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(auto_now_add=True)),
                ("is_gst", models.BooleanField(default=True)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="commerce.order",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="khataapp.party"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesVoucherItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.DecimalField(decimal_places=2, max_digits=10)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "gst_rate",
                    models.DecimalField(
                        choices=[
                            (0, "0%"),
                            (5, "5%"),
                            (12, "12%"),
                            (18, "18%"),
                            (28, "28%"),
                        ],
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commerce.product",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="commerce.salesvoucher",
                    ),
                ),
            ],
        ),
    ]
