# Generated by Django 5.2.5 on 2026-01-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_coupon_couponusage_usercoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Outstanding amount for purchase', max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Purchase invoice number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_due_date',
            field=models.DateField(blank=True, help_text='Date when payment is due', null=True),
        ),
    ]
