# Generated by Django 5.2.5 on 2026-02-03 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_commerce_ai_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commerceaisettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='StockEntry',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                        ('entry_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out')], max_length=3)),
                        ('date', models.DateField()),
                        ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockentry', to='commerce.product')),
                    ],
                ),
            ],
        ),
    ]
