# Generated by Django 5.2.5 on 2026-02-04 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_alter_commerceaisettings_id_stockentry'),
        ('khataapp', '0005_party_customer_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_source',
            field=models.CharField(default='Manual', help_text='Origin of the order (e.g. Manual, WhatsApp, API).', max_length=30),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='raw_name',
            field=models.CharField(blank=True, help_text='Raw item name when product is not matched', max_length=200),
        ),
        migrations.CreateModel(
            name='WhatsAppOrderInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=120)),
                ('raw_message', models.TextField()),
                ('parsed_items', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('manual_review', 'Manual Review')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_inbox_entries', to='commerce.order')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_orders', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_orders', to='khataapp.party')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=20)),
                ('state', models.CharField(choices=[('browsing', 'Browsing'), ('awaiting_payment', 'Awaiting Payment'), ('completed', 'Completed')], default='browsing', max_length=30)),
                ('selected_payment_mode', models.CharField(blank=True, max_length=40)),
                ('unmatched_items', models.JSONField(blank=True, default=list)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_sessions', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_sessions', to='khataapp.party')),
            ],
            options={
                'ordering': ['-last_message_at'],
                'unique_together': {('owner', 'mobile_number')},
            },
        ),
        migrations.CreateModel(
            name='WhatsAppCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='commerce.whatsappsession')),
            ],
            options={
                'unique_together': {('session', 'product')},
            },
        ),
    ]
