# Generated by Django 5.2.5 on 2026-02-15 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_stockentry'),
        ('commerce', '0011_order_agent_order_discount_amount_and_more'),
    ]

    operations = [
    ]
