# Generated by Django 5.2.5 on 2026-02-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0012_merge_20260215_1244"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="bill_sundry",
            field=models.JSONField(blank=True, default=list),
        ),
    ]

