# Generated by Django 5.2.5 on 2026-03-24 11:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_agentverification_agent_license_number_and_more'),
        ('deals', '0003_commission'),
        ('leads', '0012_leadassignmentlog_propertymedia_propertywishlist_and_more'),
        ('saas_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='agent_share_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='deal',
            name='closing_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='deal',
            name='company_share_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='deal',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='leads.property'),
        ),
        migrations.AddField(
            model_name='deal',
            name='stage',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('documentation', 'Documentation'), ('negotiation', 'Negotiation'), ('closing', 'Closing'), ('closed', 'Closed')], db_index=True, default='initiated', max_length=20),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['company', 'status', 'stage'], name='deals_deal_company_faa845_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['closing_date', 'status'], name='deals_deal_closing_eae193_idx'),
        ),
    ]
