# Generated by Django 5.2.5 on 2026-03-25 10:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_agent_commission_rate_agent_performance_score_and_more'),
        ('customers', '0002_customer_assigned_agent_and_more'),
        ('deals', '0004_deal_agent_share_percent_deal_closing_date_and_more'),
        ('leads', '0014_builder_city_builder_contact_email_builder_metadata_and_more'),
        ('saas_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='customers.customer'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('customer_payment', 'Customer Payment'), ('agent_payout', 'Agent Payout'), ('commission', 'Commission'), ('refund', 'Refund')], db_index=True, default='customer_payment', max_length=20)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], db_index=True, default='inbound', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('reference', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='agents.agent')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_payments_approved', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal_payments', to='saas_core.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='customers.customer')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='deals.deal')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['deal', 'status'], name='deals_payme_deal_id_1d9704_idx'), models.Index(fields=['company', 'payment_type', 'status'], name='deals_payme_company_e7e11b_idx'), models.Index(fields=['agent', 'status'], name='deals_payme_agent_i_d02284_idx')],
            },
        ),
    ]
