# Generated by Django 5.2.5 on 2026-03-28 12:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_deal_customer_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='adjusted_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='payment',
            name='adjustment_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='payment',
            name='adjustment_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
