# Generated by Django 5.2.5 on 2026-02-04 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=80)),
                ('target_id', models.CharField(max_length=80)),
                ('condition_text', models.CharField(blank=True, max_length=200)),
                ('is_default', models.BooleanField(default=False)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='chatbot.chatbotflow')),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=80)),
                ('node_type', models.CharField(choices=[('start', 'Start'), ('message', 'Message'), ('condition', 'Condition'), ('action', 'Action'), ('end', 'End')], max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('position_x', models.IntegerField(default=40)),
                ('position_y', models.IntegerField(default=40)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='chatbot.chatbotflow')),
            ],
            options={
                'unique_together': {('flow', 'node_id')},
            },
        ),
    ]
