# Generated by Django 5.2.5 on 2026-02-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_demo_flow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbotflow',
            options={'permissions': [('can_manage_flows', 'Can manage chatbot flows')]},
        ),
    ]
