# Generated by Django 5.2.11 on 2026-02-18 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('scanner_type', models.CharField(choices=[('laser', 'Laser'), ('ccd', 'CCD'), ('qr_2d', '2D QR'), ('bluetooth', 'Bluetooth'), ('usb_hid', 'USB HID'), ('camera', 'Camera')], max_length=20)),
                ('barcode_types_supported', models.JSONField(blank=True, default=list)),
                ('scanning_delay_ms', models.PositiveIntegerField(default=100)),
                ('auto_submit', models.BooleanField(default=True)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('default_action_after_scan', models.CharField(default='add_item', max_length=50)),
                ('camera_constraints', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanner_configs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_code', models.CharField(max_length=255)),
                ('code_type', models.CharField(default='unknown', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('scanner_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanner_config.scannerconfig')),
            ],
            options={
                'indexes': [models.Index(fields=['raw_code', 'created_at'], name='scanner_con_raw_cod_216535_idx')],
            },
        ),
    ]
