# Generated by Django 5.2.5 on 2026-03-24 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_propertyfeature_propertyimage_propertylocation_and_more'),
        ('marketing', '0002_campaign_ai_creative_url_campaign_budget_daily_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_leads', to='marketing.campaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_leads', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign', 'created_at'], name='marketing_c_campaig_218ab4_idx'), models.Index(fields=['lead', 'created_at'], name='marketing_c_lead_id_bc6c92_idx')],
                'unique_together': {('campaign', 'lead')},
            },
        ),
    ]
