# Generated by Django 5.1.3 on 2025-09-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="mobile",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="otp_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="plan",
            field=models.CharField(
                choices=[("free", "Free"), ("basic", "Basic"), ("premium", "Premium")],
                default="free",
                max_length=20,
            ),
        ),
    ]
