# Generated by Django 5.2.5 on 2025-12-11 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_dailysummary_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dailysummary",
            unique_together=set(),
        ),
    ]
