# Generated by Django 5.1.3 on 2025-12-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_dailysummary_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default="admin@gmail.com", max_length=254, unique=True
            ),
            preserve_default=False,
        ),
    ]
