# Generated by Django 5.1.3 on 2025-12-14 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "sales_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("sales_orders", models.PositiveIntegerField(default=0)),
                (
                    "purchase_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("purchase_orders", models.PositiveIntegerField(default=0)),
                (
                    "payment_received",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "payment_given",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "receivable_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "payable_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "net_position",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("total_parties", models.PositiveIntegerField(default=0)),
                ("total_transactions", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
