# Generated by Django 5.1.3 on 2025-12-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_businesssnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesssnapshot",
            name="profit_loss",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
