# Generated by Django 5.1.3 on 2026-01-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_expensecategory_expense"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_social_login",
            field=models.BooleanField(default=False),
        ),
    ]
