# Generated by Django 5.1.3 on 2026-01-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_user_is_social_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_otp_verified",
            field=models.BooleanField(default=False),
        ),
    ]
