# Generated by Django 5.2.5 on 2026-01-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_userprofile_company'),
        ('accounts', '0012_fix_otp_user_fk'),
    ]

    operations = [
    ]
