# Generated by Django 5.2.5 on 2026-03-23 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_parent_user_referral_code_user_referred_by_and_more'),
        ('saas_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Tenant company for multi-tenant isolation.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='saas_core.company'),
        ),
    ]
