# Generated by Django 5.2.11 on 2026-02-18 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('printer_type', models.CharField(choices=[('thermal_58', 'Thermal 58mm'), ('thermal_80', 'Thermal 80mm'), ('a4', 'A4')], max_length=20)),
                ('connection_type', models.CharField(choices=[('usb', 'USB'), ('bluetooth', 'Bluetooth'), ('cups', 'CUPS'), ('network', 'Network')], max_length=20)),
                ('auto_print', models.BooleanField(default=False)),
                ('include_logo', models.BooleanField(default=True)),
                ('include_qr', models.BooleanField(default=True)),
                ('include_barcode', models.BooleanField(default=True)),
                ('template_html', models.TextField(blank=True)),
                ('connection_payload', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printer_configs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrinterTestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='printer_config.printerconfig')),
            ],
        ),
    ]
