# Generated by Django 5.1.3 on 2025-09-15 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(default="My Business", max_length=100),
                ),
                (
                    "whatsapp_api_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "whatsapp_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "sms_api_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sms_sender_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("enable_auto_whatsapp", models.BooleanField(default=True)),
                ("enable_monthly_email", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("send_date", models.DateField(help_text="कब report भेजनी है")),
                ("send_time", models.TimeField(help_text="किस time पर भेजनी है")),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="ON/OFF करना है या नहीं"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mobile", models.CharField(blank=True, max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("gst", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "party_type",
                    models.CharField(
                        choices=[("customer", "Customer"), ("supplier", "Supplier")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("upi_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "bank_account_number",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
                ),
                ("is_premium", models.BooleanField(default=False)),
                (
                    "whatsapp_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("sms_number", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "credit_grade",
                    models.CharField(blank=True, default="-", max_length=5),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which user owns this party (for user-specific isolation)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="my_parties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OfflineMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                (
                    "channel",
                    models.CharField(
                        choices=[("whatsapp", "WhatsApp"), ("sms", "SMS")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="pending",
                        help_text="pending/sent/failed",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="khataapp.party",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("features", models.ManyToManyField(blank=True, to="khataapp.feature")),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "txn_type",
                    models.CharField(
                        choices=[("credit", "Credit"), ("debit", "Debit")],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "receipt",
                    models.ImageField(
                        blank=True,
                        help_text="Upload receipt slip (browse or capture from camera)",
                        null=True,
                        upload_to="receipts/",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="khataapp.party"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="auth.group",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="khataapp.plan",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="khataapp_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
