# Generated by Django 5.1.3 on 2025-12-23 09:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0005_salesvoucher_salesvoucheritem"),
        ("khataapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="gst_type",
            field=models.CharField(
                blank=True,
                choices=[("gst", "GST"), ("nongst", "Non GST")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="commerce.invoice",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="txn_mode",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("online", "Online"),
                    ("upi", "UPI"),
                    ("bank", "Bank Transfer"),
                    ("cheque", "Cheque"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="voucher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="commerce.salesvoucher",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(),
        ),
    ]
