# Generated by Django 5.2.5 on 2026-01-31 06:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_order_due_amount_order_invoice_number_and_more'),
        ('khataapp', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='credit_period',
            field=models.PositiveIntegerField(default=30, help_text='Credit period in days'),
        ),
        migrations.AddField(
            model_name='party',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='party',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Opening balance for supplier', max_digits=12),
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ledger_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out')], max_length=3)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Cost price for purchases', max_digits=10)),
                ('remaining_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Remaining stock from this batch', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(help_text='Purchase order for stock in, Sale order for stock out', on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledgers', to='commerce.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledgers', to='commerce.product')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('card', 'Card')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Cheque number, UPI ref, etc.', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(limit_choices_to={'order_type': 'PURCHASE'}, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payments', to='commerce.order')),
                ('supplier', models.ForeignKey(limit_choices_to={'party_type': 'supplier'}, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payments', to='khataapp.party')),
            ],
        ),
    ]
