# Generated by Django 5.2.5 on 2026-02-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khataapp', '0004_party_credit_period_party_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='customer_category',
            field=models.CharField(blank=True, help_text='Customer segment/category', max_length=60, null=True),
        ),
    ]
