# Generated by Django 5.2.5 on 2026-02-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khataapp', '0006_fieldagent_collectorvisit_loginlink_reminderlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinemessage',
            name='recipient_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='offlinemessage',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
