# Generated by Django 5.2.5 on 2026-03-24 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0007_agentverification_agent_license_number_and_more'),
        ('customers', '0001_initial'),
        ('leads', '0013_propertyfeature_propertyimage_propertylocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('review_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='agents.agent')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_ratings', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', 'created_at'], name='reviews_age_agent_i_5f4171_idx'), models.Index(fields=['customer', 'created_at'], name='reviews_age_custome_f47d1b_idx')],
                'unique_together': {('agent', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('review_text', models.TextField(blank=True, default='')),
                ('approved', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_reviews', to='customers.customer')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='leads.property')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['property', 'approved', 'created_at'], name='reviews_rev_propert_f67750_idx'), models.Index(fields=['customer', 'created_at'], name='reviews_rev_custome_13ae16_idx')],
                'unique_together': {('property', 'customer')},
            },
        ),
    ]
