# Generated by Django 5.2.5 on 2026-03-28 07:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('signup_bonus', 'Signup Bonus'), ('referral_referrer', 'Referral Referrer'), ('referral_invitee', 'Referral Invitee'), ('daily_login', 'Daily Login'), ('lead_conversion', 'Lead Conversion'), ('coin_to_wallet', 'Coin To Wallet')], max_length=40, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('reward_type', models.CharField(choices=[('coins', 'Coins'), ('cashback', 'Cashback'), ('spin', 'Spin'), ('scratch', 'Scratch')], default='coins', max_length=20)),
                ('coin_amount', models.PositiveIntegerField(default=0)),
                ('wallet_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('spin_count', models.PositiveIntegerField(default=0)),
                ('scratch_cards_count', models.PositiveIntegerField(default=0)),
                ('max_per_user', models.PositiveIntegerField(default=1)),
                ('max_per_day', models.PositiveIntegerField(default=1)),
                ('delay_seconds', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='SpinRewardOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('reward_type', models.CharField(choices=[('coins', 'Coins'), ('cashback', 'Cashback'), ('bonus', 'Bonus'), ('scratch', 'Scratch')], default='coins', max_length=20)),
                ('coin_amount', models.PositiveIntegerField(default=0)),
                ('wallet_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('daily_limit', models.PositiveIntegerField(default=0, help_text='0 means unlimited')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['label', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RewardCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('lifetime_earned', models.PositiveIntegerField(default=0)),
                ('lifetime_redeemed', models.PositiveIntegerField(default=0)),
                ('available_spins', models.PositiveIntegerField(default=0)),
                ('available_scratch_cards', models.PositiveIntegerField(default=0)),
                ('last_daily_login_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward_coin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('source', models.CharField(choices=[('signup', 'Signup'), ('referral', 'Referral'), ('lead_conversion', 'Lead Conversion'), ('daily_login', 'Daily Login'), ('coin_redemption', 'Coin Redemption'), ('scratch_card', 'Scratch Card'), ('spin_wheel', 'Spin Wheel'), ('manual', 'Manual')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='success', max_length=20)),
                ('coins', models.IntegerField(default=0)),
                ('cash_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reference_id', models.UUIDField(blank=True, db_index=True, editable=False, null=True, unique=True)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('narration', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('coin_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='rewards.rewardcoin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_used', models.CharField(db_index=True, max_length=24)),
                ('status', models.CharField(choices=[('tracked', 'Tracked'), ('qualified', 'Qualified'), ('rewarded', 'Rewarded')], db_index=True, default='tracked', max_length=20)),
                ('wallet_reward_reference', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('qualified_at', models.DateTimeField(blank=True, null=True)),
                ('rewarded_at', models.DateTimeField(blank=True, null=True)),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_event', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_sent', to=settings.AUTH_USER_MODEL)),
                ('invitee_reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitee_referral_events', to='rewards.rewardtransaction')),
                ('referrer_reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrer_referral_events', to='rewards.rewardtransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScratchCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.UUIDField(blank=True, db_index=True, editable=False, null=True, unique=True)),
                ('title', models.CharField(default='Mystery Reward', max_length=120)),
                ('reward_type', models.CharField(choices=[('coins', 'Coins'), ('cashback', 'Cashback'), ('bonus', 'Bonus')], default='coins', max_length=20)),
                ('coin_amount', models.PositiveIntegerField(default=0)),
                ('wallet_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('revealed', 'Revealed'), ('claimed', 'Claimed'), ('expired', 'Expired')], db_index=True, default='locked', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revealed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reward_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scratch_cards', to='rewards.rewardtransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scratch_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpinHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.UUIDField(blank=True, db_index=True, editable=False, null=True, unique=True)),
                ('reward_type', models.CharField(choices=[('coins', 'Coins'), ('cashback', 'Cashback'), ('bonus', 'Bonus'), ('scratch', 'Scratch')], default='coins', max_length=20)),
                ('coins_awarded', models.PositiveIntegerField(default=0)),
                ('wallet_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], db_index=True, default='success', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reward_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spin_history', to='rewards.rewardtransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spin_history', to=settings.AUTH_USER_MODEL)),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spin_history', to='rewards.spinrewardoption')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rewardtransaction',
            index=models.Index(fields=['user', 'source', 'created_at'], name='rewards_rew_user_id_16aa38_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardtransaction',
            index=models.Index(fields=['coin_account', 'created_at'], name='rewards_rew_coin_ac_806aff_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardtransaction',
            index=models.Index(fields=['dedupe_key'], name='rewards_rew_dedupe__c959ee_idx'),
        ),
        migrations.AddIndex(
            model_name='referralevent',
            index=models.Index(fields=['referrer', 'status'], name='rewards_ref_referre_64ac8d_idx'),
        ),
        migrations.AddIndex(
            model_name='referralevent',
            index=models.Index(fields=['code_used', 'status'], name='rewards_ref_code_us_eff26c_idx'),
        ),
        migrations.AddIndex(
            model_name='scratchcard',
            index=models.Index(fields=['user', 'status', 'created_at'], name='rewards_scr_user_id_9a3eb7_idx'),
        ),
        migrations.AddIndex(
            model_name='spinhistory',
            index=models.Index(fields=['user', 'created_at'], name='rewards_spi_user_id_b96945_idx'),
        ),
    ]
