# Generated by Django 5.2.5 on 2026-03-24 11:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saas_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_type', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('both', 'Buyer + Seller'), ('tenant', 'Tenant'), ('landlord', 'Landlord')], db_index=True, default='buyer', max_length=20)),
                ('preferred_location', models.CharField(blank=True, default='', max_length=160)),
                ('preferred_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('property_type', models.CharField(blank=True, default='', max_length=40)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='customers/avatar/')),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('district', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('state', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('pin_code', models.CharField(blank=True, db_index=True, default='', max_length=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='saas_core.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(blank=True, default='', max_length=40)),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('budget_min', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('budget_max', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('district', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('state', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='customers.customer')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'buyer_type'], name='customers_c_company_d52cb3_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['city', 'district', 'state', 'pin_code'], name='customers_c_city_5f6c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['preferred_budget', 'updated_at'], name='customers_c_preferr_93ca5a_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpreference',
            index=models.Index(fields=['customer', 'is_active'], name='customers_c_custome_0c79fa_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpreference',
            index=models.Index(fields=['city', 'property_type', 'bedrooms'], name='customers_c_city_5708f9_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpreference',
            index=models.Index(fields=['budget_min', 'budget_max'], name='customers_c_budget__a88af0_idx'),
        ),
    ]
