# Generated by Django 5.2.5 on 2026-03-25 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_agent_commission_rate_agent_performance_score_and_more'),
        ('customers', '0001_initial'),
        ('saas_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='agents.agent'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['assigned_agent', 'updated_at'], name='customers_c_assigne_e546ee_idx'),
        ),
    ]
