# Generated by Django 5.2.5 on 2026-03-28 07:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('bank', 'Bank'), ('upi', 'UPI'), ('wallet', 'Wallet')], db_index=True, max_length=20)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('beneficiary_name', models.CharField(blank=True, default='', max_length=160)),
                ('bank_name', models.CharField(blank=True, default='', max_length=120)),
                ('account_number', models.CharField(blank=True, default='', max_length=50)),
                ('ifsc_code', models.CharField(blank=True, default='', max_length=20)),
                ('upi_id', models.CharField(blank=True, default='', max_length=120)),
                ('is_default', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('disabled', 'Disabled')], db_index=True, default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_before', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('locked_before', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('locked_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('available_before', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('available_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.UUIDField(blank=True, db_index=True, editable=False, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='success', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveIndex(
            model_name='wallettransaction',
            name='wallet_wall_source_aacdce_idx',
        ),
        migrations.AddField(
            model_name='wallet',
            name='locked_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='wallet',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='wallet',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('closed', 'Closed')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='wallet',
            name='wallet_code',
            field=models.CharField(blank=True, db_index=True, max_length=24, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='wallet_uuid',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='counterparty_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparty_transactions', to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='locked_balance_after',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='narration',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='reference_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='success', max_length=20),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='reference_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='rejection_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('add_money', 'Add Money'), ('transfer', 'Transfer'), ('service', 'Service Deduction'), ('refund', 'Refund'), ('referral', 'Referral'), ('cashback', 'Cashback'), ('reward', 'Reward'), ('coin_redemption', 'Coin Redemption'), ('withdrawal', 'Withdrawal'), ('adjustment', 'Adjustment')], db_index=True, default='manual', max_length=80),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['status', 'updated_at'], name='wallet_wall_status_6ffe2a_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['currency', 'status'], name='wallet_wall_currenc_cf6910_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['user', 'created_at'], name='wallet_wall_user_id_bf675e_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['source', 'status'], name='wallet_wall_source_9c1442_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['reference'], name='wallet_wall_referen_b8b9fb_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['idempotency_key'], name='wallet_wall_idempot_442271_idx'),
        ),
        migrations.AddField(
            model_name='walletaccount',
            name='linked_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_wallet_links', to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='walletaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walletaccount',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_accounts', to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='destination_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdraw_requests', to='wallet.walletaccount'),
        ),
        migrations.AddIndex(
            model_name='withdrawrequest',
            index=models.Index(fields=['user', 'status'], name='wallet_with_user_id_38ccef_idx'),
        ),
        migrations.AddField(
            model_name='walletauditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walletauditlog',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='wallet.wallettransaction'),
        ),
        migrations.AddField(
            model_name='walletauditlog',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='walletledger',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_ledger_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walletledger',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='wallet.wallettransaction'),
        ),
        migrations.AddField(
            model_name='walletledger',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='wallettransfer',
            name='receiver_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='wallet.walletaccount'),
        ),
        migrations.AddField(
            model_name='wallettransfer',
            name='receiver_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfer', to='wallet.wallettransaction'),
        ),
        migrations.AddField(
            model_name='wallettransfer',
            name='receiver_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='wallettransfer',
            name='sender_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transfers', to='wallet.walletaccount'),
        ),
        migrations.AddField(
            model_name='wallettransfer',
            name='sender_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transfer', to='wallet.wallettransaction'),
        ),
        migrations.AddField(
            model_name='wallettransfer',
            name='sender_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to='wallet.wallet'),
        ),
        migrations.AddIndex(
            model_name='walletaccount',
            index=models.Index(fields=['user', 'account_type', 'status'], name='wallet_wall_user_id_5f5834_idx'),
        ),
        migrations.AddIndex(
            model_name='walletaccount',
            index=models.Index(fields=['upi_id'], name='wallet_wall_upi_id_d42825_idx'),
        ),
        migrations.AddIndex(
            model_name='walletaccount',
            index=models.Index(fields=['account_number', 'ifsc_code'], name='wallet_wall_account_5279b9_idx'),
        ),
        migrations.AddIndex(
            model_name='walletauditlog',
            index=models.Index(fields=['wallet', 'created_at'], name='wallet_wall_wallet__5a3263_idx'),
        ),
        migrations.AddIndex(
            model_name='walletauditlog',
            index=models.Index(fields=['action', 'created_at'], name='wallet_wall_action_9bd172_idx'),
        ),
        migrations.AddIndex(
            model_name='walletledger',
            index=models.Index(fields=['wallet', 'created_at'], name='wallet_wall_wallet__09dcd5_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransfer',
            index=models.Index(fields=['sender_wallet', 'created_at'], name='wallet_wall_sender__ef9393_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransfer',
            index=models.Index(fields=['receiver_wallet', 'created_at'], name='wallet_wall_receive_a324a7_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransfer',
            index=models.Index(fields=['status', 'created_at'], name='wallet_wall_status_7ec51d_idx'),
        ),
    ]
