# Generated by Django 5.2.5 on 2026-03-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='blocked_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='payout',
            name='fraud_flag',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='payout',
            name='is_withheld',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
