# Generated by Django 5.2.5 on 2026-03-23 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0007_alter_featuresettings_feature'),
        ('crm', '0002_localshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], db_index=True, default='info', max_length=10)),
                ('source', models.CharField(blank=True, default='', max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_alerts', to='core_settings.companysettings')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'severity', 'resolved', 'created_at'], name='crm_adminal_company_14fd5a_idx')],
            },
        ),
        migrations.CreateModel(
            name='DashboardCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=80)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('ttl_seconds', models.PositiveIntegerField(default=900)),
                ('refreshed_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_cache', to='core_settings.companysettings')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'key'], name='crm_dashboa_company_3eab48_idx')],
                'unique_together': {('company', 'key')},
            },
        ),
    ]
