# Generated by Django 5.2.5 on 2026-03-24 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_adminalert_dashboardcache'),
        ('leads', '0011_lead_followup_channel_lead_last_followup_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calllog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='calllog',
            name='external_call_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='calllog',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='calllog',
            name='missed_call',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='calllog',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='calllog',
            name='recording_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='calllog',
            name='telephony_provider',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='crm.customerprofile'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['lead', 'created_at'], name='crm_calllog_lead_id_3dc205_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['customer', 'created_at'], name='crm_calllog_custome_a4646c_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['missed_call', 'created_at'], name='crm_calllog_missed__0fb595_idx'),
        ),
    ]
