# Generated by Django 5.2.5 on 2026-03-28 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_calllog_options_calllog_external_call_id_and_more'),
        ('leads', '0016_lead_customer_type_lead_is_overdue_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OverrideLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('price_override', 'Price Override'), ('commission_override', 'Commission Override'), ('payment_adjustment', 'Payment Adjustment'), ('deal_status_override', 'Deal Status Override'), ('feature_override', 'Feature Override'), ('inventory_hold', 'Inventory Hold')], db_index=True, max_length=40)),
                ('target_model', models.CharField(db_index=True, max_length=120)),
                ('target_object_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('old_value', models.JSONField(blank=True, default=dict)),
                ('new_value', models.JSONField(blank=True, default=dict)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='override_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['target_model', 'action_type', 'timestamp'], name='crm_overrid_target__502437_idx')],
            },
        ),
        migrations.CreateModel(
            name='UnitHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold_start', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('hold_end', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('released', 'Released')], db_index=True, default='active', max_length=20)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_holds', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='leads.property')),
            ],
            options={
                'ordering': ['-hold_start'],
                'indexes': [models.Index(fields=['unit', 'status', 'hold_end'], name='crm_unithol_unit_id_5b4620_idx'), models.Index(fields=['agent', 'status'], name='crm_unithol_agent_i_545f3d_idx')],
            },
        ),
    ]
