# Generated by Django 5.2.5 on 2026-03-29 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_agent_assigned_location_agent_current_location'),
        ('crm', '0005_overridelog_unithold'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=80)),
                ('title', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('badge', 'Badge'), ('reward', 'Reward'), ('rank', 'Rank')], db_index=True, default='badge', max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('points', models.PositiveIntegerField(default=0)),
                ('achieved_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='agents.agent')),
            ],
            options={
                'ordering': ['-achieved_at'],
                'indexes': [models.Index(fields=['agent', 'kind', 'achieved_at'], name='crm_agentac_agent_i_ca3fec_idx'), models.Index(fields=['code', 'achieved_at'], name='crm_agentac_code_328bb7_idx')],
                'unique_together': {('agent', 'code')},
            },
        ),
        migrations.CreateModel(
            name='AgentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_date', models.DateField(db_index=True)),
                ('leads_assigned', models.PositiveIntegerField(default=0)),
                ('leads_closed', models.PositiveIntegerField(default=0)),
                ('response_time_seconds', models.PositiveIntegerField(default=0)),
                ('points', models.IntegerField(db_index=True, default=0)),
                ('target_points', models.PositiveIntegerField(default=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_scores', to='agents.agent')),
            ],
            options={
                'ordering': ['-score_date', '-points', '-created_at'],
                'indexes': [models.Index(fields=['agent', 'score_date'], name='crm_agentsc_agent_i_19c4d1_idx'), models.Index(fields=['points', 'score_date'], name='crm_agentsc_points_69b323_idx')],
                'unique_together': {('agent', 'score_date')},
            },
        ),
    ]
