# Generated by Django 5.2.5 on 2026-03-25 08:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0014_builder_city_builder_contact_email_builder_metadata_and_more'),
        ('saas_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='banks/logos/')),
                ('website', models.URLField(blank=True, default='')),
                ('support_email', models.EmailField(blank=True, default='', max_length=254)),
                ('support_phone', models.CharField(blank=True, default='', max_length=30)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='saas_core.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('property_type', models.CharField(blank=True, choices=[('house', 'House'), ('flat', 'Flat'), ('apartment', 'Apartment'), ('villa', 'Villa'), ('land', 'Land'), ('commercial', 'Commercial')], default='', max_length=20)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('8.50'), max_digits=6)),
                ('loan_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tenure_years', models.PositiveIntegerField(default=20)),
                ('emi_estimate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('min_income_required', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='loans.bank')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_products', to='saas_core.company')),
            ],
            options={
                'ordering': ['bank__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tenure_years', models.PositiveIntegerField(default=20)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('existing_emi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('emi_estimate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('eligibility_ratio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('applied', 'Applied'), ('eligible', 'Eligible'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='applied', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='saas_core.company')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_applications', to='leads.property')),
                ('loan_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='loans.loanproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bank',
            index=models.Index(fields=['company', 'active'], name='loans_bank_company_07ae04_idx'),
        ),
        migrations.AddIndex(
            model_name='bank',
            index=models.Index(fields=['slug'], name='loans_bank_slug_2f366b_idx'),
        ),
        migrations.AddIndex(
            model_name='loanproduct',
            index=models.Index(fields=['company', 'active'], name='loans_loanp_company_d2722f_idx'),
        ),
        migrations.AddIndex(
            model_name='loanproduct',
            index=models.Index(fields=['property_type', 'active'], name='loans_loanp_propert_e45b7a_idx'),
        ),
        migrations.AddIndex(
            model_name='loanproduct',
            index=models.Index(fields=['interest_rate'], name='loans_loanp_interes_7ff179_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['company', 'status', 'created_at'], name='loans_loana_company_64fc98_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['applicant', 'status'], name='loans_loana_applica_106cd9_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['property', 'status'], name='loans_loana_propert_c1410d_idx'),
        ),
    ]
