# Generated by Django 5.2.5 on 2026-03-24 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_builder_city_builder_contact_email_builder_metadata_and_more'),
        ('voice', '0002_voicecall'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCallTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(choices=[('bot', 'Bot'), ('lead', 'Lead'), ('system', 'System')], db_index=True, max_length=10)),
                ('message', models.TextField(blank=True, default='')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='voicecall',
            name='qualification_status',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='voicecall',
            name='qualified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='voicecall',
            name='structured_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='voicecall',
            name='transcript',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='voicecall',
            index=models.Index(fields=['qualification_status', 'qualified'], name='vc_qual_status_idx'),
        ),
        migrations.AddField(
            model_name='voicecallturn',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='voice.voicecall'),
        ),
        migrations.AddIndex(
            model_name='voicecallturn',
            index=models.Index(fields=['call', 'sequence'], name='vc_turn_seq_idx'),
        ),
    ]
