# Generated by Django 5.2.11 on 2026-02-18 09:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('barcode', models.CharField(db_index=True, max_length=128, unique=True)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=12)),
                ('b2b_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('b2c_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fast_moving', models.BooleanField(default=False)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('b2b', 'B2B'), ('b2c', 'B2C'), ('pos', 'POS'), ('quick', 'Quick')], max_length=20)),
                ('min_qty', models.PositiveIntegerField(default=1)),
                ('max_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('override_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_price_rules', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_qty', models.IntegerField(default=0)),
                ('reserved_qty', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_inventories', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='warehouse.warehouse')),
            ],
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku', 'barcode'], name='products_pr_sku_13ed68_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['fast_moving'], name='products_pr_fast_mo_e23bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='productpricerule',
            index=models.Index(fields=['product', 'channel', 'is_active'], name='products_pr_product_b158b8_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseinventory',
            index=models.Index(fields=['warehouse', 'available_qty'], name='products_wa_warehou_3ec180_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouseinventory',
            unique_together={('warehouse', 'product')},
        ),
    ]
